#!/usr/bin/env bash
# Configure Nginx server so that /redirect_me is redirecting to another page.

sudo apt-get update
sudo apt-get install -y nginx


sudo sh -c 'echo "server {
     listen      80 default_server;
     listen      [::]:80 default_server;

     location /redirect_me {
         return 301 http://reuszed.com/;

     }

     root        /var/www/html;
     index       index.html index.htm;
}" > /etc/nginx/sites-available/default'

sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/

sudo service nginx restart
