#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 that containsceci n'est pas une page.


sudo apt-get update -y
sudo apt-get install nginx -y
sudo touch /var/www/html/index.html
sudo sh -c "echo 'Hello World!' > /var/www/html/index.html"
sudo touch /var/www/html/404.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
SERVER_CONFIG="server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	# Add index.php to the list if you are using PHP
	index index.html index.htm index.nginx-debian.html;

	server_name _;

	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
			rewrite ^ https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
	error_page 404 /404.html;
	location = /404.html{
		internal;
	}
}"
sudo sh -c "echo '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"
sudo service nginx restart
