#!/usr/bin/env bash
# script that sets up nginx
sudo apt-get update
sudo apt-get install haproxy

echo "

frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    mode http
    balance roundrobin
    server 181572-web-01 18.206.198.30 check
    server 181572-web-02 18.234.130.203 check
" | sudo tee /etc/haproxy/haproxy.cfg
sudo service haproxy restart
